"""
Application settings
Generated by yeoman generator-django-ana <%= version %> on <%= date %>.
"""

from django.apps import AppConfig


class <%= pascalName %>CoreConfig(AppConfig):
    name = '<%= name %>_core'
    verbose_name = "<%= verboseName %>"

    def ready(self):
        # noinspection PyUnresolvedReferences
        import <%= name %>_core.signals
