"""
Application signal handling
Generated by yeoman generator-django-ana <%= version %> on <%= date %>.
"""

from django import dispatch
from django.db.models import Q
# from ninecms import signals


# @dispatch.receiver(signals.block_signal)
