"""
Application testing
Generated by yeoman generator-django-ana <%= version %> on <%= date %>.
"""
from django.test import TestCase
from django.urls import reverse


class <%= pascalName %>Tests(TestCase):
    def test(self):
        response = self.client.get(reverse('index'))
