"""
URL routing for core app
Generated by yeoman generator-django-ana <%= version %> on <%= date %>.
"""
from django.conf.urls import url
from <%= name %>_core import views

urlpatterns = [
    url(r'^contact/', views.ContactView.as_view(), name='contact'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]
